[pytest]
pythonpath = .
addopts =
    --ignore=tests/test_application_service.py
    --ignore=tests/test_audit_repository.py
    --ignore=tests/test_campaigns_handler.py
    --ignore=tests/test_repositories.py
    --ignore=tests/test_review_service.py
    --ignore=tests/test_reward_repository.py
    --ignore=tests/test_start_handler.py
    --ignore=tests/test_support_service.py
    --ignore=tests/test_ticket_repository.py
    --ignore=tests/test_user_service.py
    --ignore=tests/test_utils.py
    --ignore=tests/test_container.py
    --ignore=tests/test_core_imports.py